version: "3.8"

services:
  app:
    build: .
    platform: linux/amd64
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_NAME=nestjs_db
      - JWT_SECRET=secretKey
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nestjs_db
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
